### PR TITLE
248_Create_Entities

### PR DESCRIPTION
**Pull request by iryna-onyshkevych**
Entities Card, Category, Person, Transaction, TransactionType, Wallet added

### CODE REVIEW

**Review by RomanHulovatyi — APPROVED** [review]
Very nice!

**Review by DmytroKhmelovskyi — APPROVED** [review]
All right

**Review by Pain1x — CHANGES_REQUESTED** [review]
SURE

**Review by cptntr — CHANGES_REQUESTED** [review]
Active/Inactive flag needed in Person, Wallet

**Review by RomanHulovatyi — APPROVED** [review]

**Review by Pain1x — APPROVED** [review]
OK

**Review by cptntr — APPROVED** [review]
Looks nice to me

**Pull request merged**
